### ISSUE TITLE
最強のフロントエンドDojotoolkit

### ISSUE THREAD

**Issue by mintmylove** [h-iwata/dojo-coffeescript-jquery-boilerplate#1]
h-iwata 様

お忙しいところ、すいません。

dojo のテストについてのブログを、以前拝見しました。
最近に、もう一度、読ませていただこうと思ったのですが、
http://web-programmers-blog.com/frontend/dojo/doh-dojo-objective-harness-javascript-test-framework/
は、データベースエラーと表示されて、読むことができませんでした。

ぜひ、拝見したいのですが、どいのようにすれば、読むことができるでしょうか？

ご教授いただければ、幸いに存じます。
よろしく、お願いいたします
　　　　　　　　　　　　　古川

**Comment by h-iwata** [comment]
ああ申し訳ないです！
今週の土日に再開します！ありがとうございます

**Comment by h-iwata** [comment]
再開しました
http://web-programmers-blog.com/frontend/dojo/doh-dojo-objective-harness-javascript-test-framework/
現在はReactをdojoのように使うための記事を書いてますが、
現代流のdojoの使い方やdojo2についてもその内書いていきます

**Comment by mintmylove** [comment]
h-iwata 様

お忙しいところ、すいません。
再開していただきまして、ありがとうございます。

h-iwata 様のページは最高に素晴らしい。
参考にして、勉強いたします。

今後とも、よろしく、お願いいたします。

　　　　　　　　　　　　　　　　　　　　　古川
